# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50, verbose_name='\u0433\u043e\u0440\u043e\u0434')),
                ('organizer', models.CharField(default='', max_length=200, verbose_name='\u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0442\u043e\u0440')),
                ('name', models.CharField(max_length=1000, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('start_date', models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('description', models.CharField(max_length=1000, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('addres', models.CharField(default='', max_length=200, verbose_name='\u043c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='\u043f\u043e\u0441\u0442\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u0441\u043e\u0431\u044b\u0442\u0438\u0435',
                'verbose_name_plural': '\u0441\u043e\u0431\u044b\u0442\u0438\u044f',
            },
        ),
    ]
