# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='', max_length=200, verbose_name='\u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
