# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eManager', '0002_auto_20161101_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addres',
            field=models.CharField(default='', max_length=200, verbose_name='место проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='постер'),
        ),
    ]
