# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eManager', '0002_auto_20161128_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=50, verbose_name='\u043b\u043e\u0433\u0438\u043d')),
                ('password', models.CharField(default='', max_length=20, verbose_name='\u043f\u0430\u0440\u043e\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
        ),
    ]
