# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eManager', '0004_auto_20161214_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
