# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eManager', '0005_myuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
    ]
