# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eManager', '0006_remove_myuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
